name: Deploy Lambda Function 2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build and Deploy with SAM
      run: |
        sam build
        sam deploy --no-confirm-changeset --stack-name TranscriptProcessorStack --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
