name: Deploy Lambda Function Using Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Configure AWS Region
    - name: Set AWS Region
      run: |
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t my-lambda-function .

    # Step 5: Tag Docker Image
    - name: Tag Docker Image
      run: |
        docker tag my-lambda-function:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-lambda-function:latest

    # Step 6: Push Docker Image to Amazon ECR
    - name: Push Docker Image to Amazon ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-lambda-function:latest

    # Step 7: Deploy to AWS Lambda
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name TranscriptProcessorFunction \
          --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-lambda-function:latest \
          --region ${{ secrets.AWS_REGION }}
